services:
  cms:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '${APP_PORT:-8080}:8080'
    env_file:
      - .env
    volumes:
      - './umbraco/Data/Umbraco.sqlite.db:/app/umbraco/Data/Umbraco.sqlite.db'
      - './wwwroot/media:/app/wwwroot/media'
      - 'media-cache:/app/umbraco/TEMP/MediaCache'
      - 'data-protection-keys:/root/.aspnet/DataProtection-Keys'
    restart: unless-stopped
    profiles: [backend]

volumes:
  media-cache:
  data-protection-keys:
