services:
  frontend-dev:
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    ports:
      - 3000:3000
    stop_grace_period: 0s
    profiles: [frontend-dev]

  frontend-prod:
    build:
      context: ./
      dockerfile: ./docker/prod.Dockerfile
      # args:
      #   ENV_VARIABLE: ${ENV_VARIABLE}
      #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    profiles: [frontend-prod]
