services:
    frontend-dev:
        build:
            context: ./
            dockerfile: ./docker/dev.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
        restart: unless-stopped
        ports:
            - ${APP_PORT:-3000}:3000
        stop_grace_period: 0s
        profiles: [ frontend-dev ]

    frontend-prod:
        build:
            context: ./
            dockerfile: ./docker/prod.Dockerfile
            args:
                NEXT_PUBLIC_UMBRACO_BASE_URL: ${NEXT_PUBLIC_UMBRACO_BASE_URL}
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - ${APP_PORT:-3000}:3000
        profiles: [ frontend-prod ]
