services:
    frontend-dev:
        build:
            context: ./
            dockerfile: ./docker/dev.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
        restart: always
        ports:
            - ${APP_PORT:-3000}:3000
        stop_grace_period: 0s
        profiles: [ frontend-dev ]

    frontend-prod:
        build:
            context: ./
            dockerfile: ./docker/prod.Dockerfile
            args:
                NEWSLETTER_ENDPOINT: ${NEWSLETTER_ENDPOINT}
                NEWSLETTER_LIST_ID: ${NEWSLETTER_LIST_ID}
        restart: always
        ports:
            - ${APP_PORT:-3000}:3000
        profiles: [ frontend-prod ]
