services:
  backend-queue-dev:
    build:
      context: ./
      dockerfile: ./docker/cli.Dockerfile
      args:
          WWWUSER: "${WWWUSER:-1000}"
          WWWGROUP: "${WWWGROUP:-1000}"
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: php craft queue/listen
    profiles: [backend-dev]

  backend-web-dev:
    build:
      context: ./
      dockerfile: ./docker/web.Dockerfile
      args:
          WWWUSER: "${WWWUSER:-1000}"
          WWWGROUP: "${WWWGROUP:-1000}"
    ports:
      - "8080:8080"
      - "5173:5173"
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    profiles: [backend-dev]

  mysql:
    image: mysql:8.0.37
    ports:
      - ${FORWARDED_DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${CRAFT_DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${CRAFT_DB_DATABASE}"
      MYSQL_USER: "${CRAFT_DB_USER}"
      MYSQL_PASSWORD: "${CRAFT_DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "db_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${CRAFT_DB_PASSWORD}"]
      interval: 5s
    profiles: [database]

volumes:
  db_data:
