services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '${APP_PORT:-8080}:8080'
    env_file:
      - .env
    volumes:
      - './src/MethodConf.Cms/umbraco/Data/Umbraco.sqlite.db:/app/umbraco/Data/Umbraco.sqlite.db'
      - './src/MethodConf.Cms/wwwroot/media:/app/wwwroot/media'
      - 'cache:/app/umbraco/Data/TEMP'
      - 'data-protection-keys:/root/.aspnet/DataProtection-Keys'
    restart: unless-stopped
    profiles: [ backend ]
  sqlite-web:
    build:
      context: https://github.com/coleifer/sqlite-web.git
      dockerfile: docker/Dockerfile
    ports:
      - "${SQLITE_WEB_PORT:-8080}:8080"
    volumes:
      - ./src/MethodConf.Cms/umbraco/Data:/data
    env_file:
      - .env
    command: >
      sqlite_web /data/Umbraco.sqlite.db
      --password "$SQLITE_WEB_PASSWORD"
      --host 0.0.0.0
    profiles: [ sqlite-web ]
  maildev:
    image: maildev/maildev
    ports:
      - '${SMTP_PORT:-1025}:1025'
      - '${EMAIL_GUI_PORT:-1080}:1080'
    profiles: [ local-email ]

volumes:
  cache:
  data-protection-keys:
