// <auto-generated />
using System;
using MethodConf.Cms.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MethodConf.Cms.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MethodConf.Cms.Domain.SessionFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeakerRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SessionFeedback");
                });
#pragma warning restore 612, 618
        }
    }
}
