name: Frontend Release

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-**'

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      release-version: ${{ steps.semantic.outputs.release-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: npm install -g semantic-release semantic-release-monorepo conventional-changelog-conventionalcommits @semantic-release/exec

      - name: Create Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./frontend
        run: npx semantic-release

  docker:
    needs: release
    if: ${{ needs.release.outputs.new-release-published == 'true' }}
    uses: ./.github/workflows/frontend-docker-publish.yml
    with:
      version: ${{ needs.release.outputs.release-version }}
      next_public_umbraco_base_url: https://cms.methodconf.com/
      next_public_site_url: https://www.methodconf.com/
    secrets: inherit
