name: Lint Build Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_UMBRACO_BASE_URL: https://cms.methodconf.com/
      NEXT_PUBLIC_SITE_URL: https://www.methodconf.com/
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build
