name: Lint Build Test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changed-files.outputs.frontend_any_changed }}
      backend: ${{ steps.changed-files.outputs.backend_any_changed }}
      workflows: ${{ steps.changed-files.outputs.workflows_any_changed }}
    steps:
      - uses: actions/checkout@v6
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files_yaml: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            workflows:
              - '.github/workflows/**'

  lint-build-frontend:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.workflows == 'true' }}
    defaults:
      run:
        working-directory: './frontend'
    env:
      NEXT_PUBLIC_UMBRACO_BASE_URL: ${{ secrets.NEXT_PUBLIC_UMBRACO_BASE_URL }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: './frontend/.nvmrc'
      - run: npm install
      - run: npm run lint
      - run: npm run build

  lint-build-test-backend:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.workflows == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore
      - run: dotnet format --verify-no-changes --verbosity diagnostic
      - run: dotnet build
      - run: dotnet test
